/// Flutter icons MyFlutterApp
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MydrawerIcons {
  MydrawerIcons._();

  static const _kFontFam = 'drawer';
  static const String? _kFontPkg = null;

  static const IconData goals = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData help = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData schedule = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData about = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData datestoremember = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData weekatglance = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData habittracker = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData timetable = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData bookshelf = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData book = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
